# fly.toml app configuration file generated for thermae-redis on 2023-11-15T19:44:09-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "thermae-redis"
primary_region = "ord"


[mount]
  destination = "/data"
  source = "redis_server"

[[files]]
  guest_path = "/usr/local/etc/redis/redis.conf"
  local_path = "./redis.conf"
